spring:
  application:
    name: slack-service
  config:
    import: optional:file:.env-slack[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}

slack:
  token: ${SLACK_TOKEN}

gemini:
  api-key: ${GEMINI_API_KEY}
