spring:
  application:
    name: slack-service
  config:
    import: optional:file:.env-slack[.properties]

  datasource:
    url: ${SLACK_URL}
    username: ${SLACK_USER}
    password: ${SLACK_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 19098

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

slack:
  token: ${SLACK_TOKEN}

gemini:
  api-key: ${GEMINI_API_KEY}
