spring:
  application:
    name: auth-service
  config:
    import:
      - optional:file:.env[.properties]
  datasource:
    url: ${AUTH_URL}
    username: ${AUTH_USER}
    password: ${AUTH_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # (처음엔 create, 운영에선 none 권장)
    show-sql: true       # SQL 로그 출력
    properties:
      hibernate:
        format_sql: true # SQL을 보기 좋게 출력
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public

server:
  port: 19096

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

service:
  jwt:
    access-expiration: 36000000 # 액세스 토큰 만료시간 (10시간 = 36,000,000ms)
    refresh-expiration: 604800000 # 리프레시 토큰 만료시간 (7일 = 604,800,000ms)
    secret-key: ${JWT_KEY}
