spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
cloud:
  gateway:
    routes:
      - id: product-service
        uri: lb://product-service
        predicates:
          - Path=/product/**

      - id: delivery-service
        url: lb://delivery-service
        predicates:
          - Path=/delivery/**

      - id: hub-service
        url: lb://hub-service
        predicates:
          - Path=/hub/**

      - id: order-service
        uri: lb://order-service
        predicates:
          - Path=/order/**

      - id: user-service
        url: lb://user-service
        predicates:
          - Path=/user/**

    discovery:
      locator:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

server:
  port: 19091