spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/deliveries/**

        - id: hub-service
          uri: lb://hub-service
          predicates:
            - Path=/hubs/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**

        - id: user-service
          uri: lb://user-service
            - Path=/user/**

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auths/**

      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

server:
  port: 19091