### 회원 생성 MASTER
POST http://localhost:19091/auths/signUp
Content-Type: application/json

{
  "username": "manager3",
  "nickname": "mgr3",
  "email": "mgr3@email.com",
  "password": "Hash678!",
  "role": "MASTER"
}

### 회원 생성 COMPANY MANAGER
POST http://localhost:19091/auths/signUp
Content-Type: application/json

{
  "username": "compmgr1",
  "nickname": "cpmgr1",
  "email": "cpmgr1@email.com",
  "password": "Hash123!",
  "role": "COMPANY_MANAGER"
}

### 로그인 1
POST http://localhost:19091/auths/login
Content-Type: application/json

{
  "email": "mgr1@email.com",
  "password": "Hash123!"
}

> {%
    client.global.set("access_token", response.body.data.accessToken)
    client.log("test: " + client.global.get("access_token"))
%}

### 로그인 2
POST http://localhost:19091/auths/login
Content-Type: application/json

{
  "email": "mgr2@email.com",
  "password": "Hash456!"
}

> {%
    client.global.set("access_token", response.body.data.accessToken)
    client.log("test: " + client.global.get("access_token"))
%}

### 로그인 3
POST http://localhost:19091/auths/login
Content-Type: application/json

{
  "email": "mgr3@email.com",
  "password": "Hash678!"
}

> {%
    client.global.set("access_token", response.body.data.accessToken)
    client.log("test: " + client.global.get("access_token"))
%}

### 로그인 4
POST http://localhost:19091/auths/login
Content-Type: application/json

{
  "email": "cpmgr1@email.com",
  "password": "Hash123!"
}

> {%
    client.global.set("access_token", response.body.data.accessToken)
    client.log("test: " + client.global.get("access_token"))
%}

### 로그 아웃
POST http://localhost:19091/auths/logout
Authorization:Bearer {{access_token}}

### 업체 관리자 승인
POST http://localhost:19091/auths/approve/6

### 회원 목록 조회
GET http://localhost:19091/auths

### 회원 상세 조회
GET http://localhost:19091/auths/1

### 회원 검색 1
GET http://localhost:19091/auths/search?email=mgr3@email.com

### 회원 검색 2
GET http://localhost:19091/auths/search?email=mgr1@email.com

### 내 정보 조회
GET http://localhost:19091/auths/me
Authorization:Bearer {{access_token}}

### 내 정보 수정
PUT http://localhost:19091/auths/me
Content-Type: application/json
Authorization:Bearer {{access_token}}

{
  "username": "manager1",
  "nickname": "mgr1"
}



