spring:
  application:
    name: company-service
  config:
    import: optional:file:.env-company[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${COMPANY_SERVICE_URL}
    username: ${COMPANY_SERVICE_USERNAME}
    password: ${COMPANY_SERVICE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 19099

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka
