dependencies {
    implementation 'com.slack.api:slack-api-client:1.7.0' // slack api
    implementation 'org.springframework.boot:spring-boot-starter-webflux' // webclient
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client' // 유레카 클라이언트
    implementation 'org.springframework.boot:spring-boot-starter-web' // 스프링 웹
    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign' // feign
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa' // jpa
    runtimeOnly 'org.postgresql:postgresql'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    implementation project(':common') // 공통 모듈
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:2024.0.2"
    }
}