dependencies {
    implementation 'org.projectlombok:lombok'
    runtimeOnly 'org.postgresql:postgresql' // postgres
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa' // jpa

	implementation project(':common') // 공통 모듈
	implementation 'org.springframework.boot:spring-boot-starter-web' // 스프링 웹
	implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client' // 유레카 클라이언트
	implementation 'org.springframework.cloud:spring-cloud-starter-openfeign' // 페인 클라이언트
}