dependencies {
    implementation 'org.projectlombok:lombok' // 롬복 컴파일 시
    annotationProcessor 'org.projectlombok:lombok'// 롬복 코드 생성
    runtimeOnly 'org.postgresql:postgresql'   // 포스트그레스
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa' // jpa
    implementation 'org.springframework.boot:spring-boot-starter-validation' // @Valid
	implementation project(':common') // 공통 모듈
	implementation 'org.springframework.boot:spring-boot-starter-web' // 스프링 웹
	implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client' // 유레카 클라이언트
	implementation 'org.springframework.cloud:spring-cloud-starter-openfeign' // 페인 클라이언트
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:2024.0.2"
	}
}