spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${HUB_DB_URL}
    username: ${HUB_DB_USERNAME}
    password: ${HUB_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true


server:
  port: 19094