spring:
  application:
    name: delivery-service
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://localhost:19098
      discovery:
        enabled: true
        service-id: config-server
      profile: default

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
